// made by Scarlet and n1
GTCEuStartupEvents.registry("gtceu:machine", event => {
    event.create("vacuum_chemical_reaction_chamber", "multiblock")
        .machine((holder) => new $VacuumChemicalReactorMachine(holder))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType("vacuum_chemical_reaction_chamber")
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, $StarTRecipeModifiers.VACUUM_CHEMICAL_REACTION_CHAMBER])
        .appearanceBlock(() => Block.getBlock("kubejs:enriched_naquadah_machine_casing"))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aacbbbcaaaaa", "aagaaagaaaaa", "aagaaagaaaaa", "aagaaagaaaaa", "aacbbbcaaaaa")
            .aisle("aacbbbcaaaaa", "aaadfdaaaaaa", "aaadfdaaaaaa", "aaadfdaaaaaa", "aacbibcaaaaa")
            .aisle("aacbbbcaaaaa", "aaafhfaaaaaa", "aaafhfaaaaaa", "aaafhfaaaaaa", "aaciiicaaaaa")
            .aisle("aacbbbcaaaaa", "aaadddaaaaaa", "aaadhdaaaaaa", "aaadddaaaaaa", "aacbibcaaaaa")
            .aisle("aacbbbcccccb", "aaabbbbbbbbb", "aaabhbbibibb", "aaabbbbbbbbb", "aacbbbcccccb")
            .aisle("agbbbbbbbbbc", "bgbbaaaaaaaj", "bbbbhhhhhhaj", "bgbbaaaaaaaj", "agbbjjjjjjjc")
            .aisle("bgbbbbbbbbbb", "abababbbbbbb", "ababhbbbbhbb", "abababbbbbbb", "bgbbjbbbbbbb")
            .aisle("bbbbbbaaacaa", "abababaaddda", "akhhhbaadhda", "abababaaddda", "bbbbjbaaacaa")
            .aisle("bgbbbbabacab", "ababajabdddb", "ababhjabdhdb", "ababajabdddb", "bgbbjbabacab")
            .aisle("aggbbbabcccb", "bgbbababdddb", "bbbbhbaihhhi", "bgbbababdddb", "aggbjbabcccb")
            .aisle("aaabcbabaaab", "aaabbbabdddb", "aaabebabfffb", "aaabbbabdddb", "aaabcbabaaab")
            .where("a", Predicates.any())
            .where("b", Predicates.blocks("kubejs:enriched_naquadah_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)).setMinGlobalLimited(1)
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities($StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0)))
            .where("c", Predicates.blocks("kubejs:enriched_naquadah_firebox_casing"))
            .where("d", Predicates.blocks("kubejs:polycarbonate_casing"))
            .where("e", Predicates.controller(Predicates.blocks(definition.get())))
            .where("f", Predicates.blocks("gtceu:fusion_glass"))
            .where("g", Predicates.blocks("gtceu:naquadah_alloy_frame"))
            .where("h", Predicates.blocks("kubejs:enriched_naquadah_pipe_casing"))
            .where("i", Predicates.blocks("kubejs:enriched_naquadah_engine_intake_casing"))
            .where("j", Predicates.blocks("gtceu:molybdenum_disilicide_coil_block"))
            .where("k", $StarTVacuumPumpPredicates.vacuumPumps())
            .build())
        .workableCasingModel("kubejs:block/casings/naquadah/casing", "gtceu:block/machines/chemical_reactor");
});