GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('dual_chambered_vacuum_complex', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuum_chemical_reaction_chamber')
        .recipeModifiers([$StarTRecipeModifiers.THOUGHPUT_BOOSTING, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(() => Block.getBlock('kubejs:enriched_naquadah_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aabaa ddddd ", "a   a  bbbb ", "b   b  bbb  ", "b   a       ", "aabaa       ", "            ", "            ", "            ", "            ", "            ", "            ")
            .aisle("abbba dddddd", "bfffb b   b ", "bfgfb b   b ", "bfffb jbbbj ", "abbba jb bj ", "  b   jb bj ", "  b   jb bj ", "      jb bj ", "      bbbbb ", "            ", "            ")
            .aisle("dddddddddddd", "b   bb     b", "b   bb     b", "b   b bfffb ", "bbbbb bfhfb ", " bbb  bfhfb ", " bbb  bfhfb ", "  b   bfhfb ", "  b   bfffb ", "            ", "            ")
            .aisle("dddddddddddd", "b   bb     b", "b   bb     b", "b   bbbfffb ", "bb bbbbf h  ", "bb bb bf h  ", "bbibb bf h  ", " bib  bf h  ", " bib  bfifb ", "  i     i   ", "  iiiiiii   ")
            .aisle("dddddddddddd", "b   bb     b", "b   bb     b", "b   b bfffb ", "bbbbb bfhfb ", " bbb  bfhfb ", " bbb  bfhfb ", "  b   bfhfb ", "  b   bfffb ", "            ", "            ")
            .aisle("abbbaddddddd", "bfffb b   b ", "bfgfb b   b ", "bfffb abbba ", "abbba ab ba ", "  b   ab ba ", "  b   ab ba ", "      ab ba ", "      bbbbb ", "            ", "            ")
            .aisle("aabaa ddddd ", "a   a  beb  ", "b   b  bbb  ", "a   a       ", "aabaa       ", "            ", "            ", "            ", "            ", "            ", "            ")
            .where("a", Predicates.blocks("gtceu:red_steel_frame"))
            .where("b", Predicates.blocks("kubejs:enriched_naquadah_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)).setMinGlobalLimited(1)
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities($StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0)))
            .where(" ", Predicates.any())
            .where("d", Predicates.blocks("kubejs:enriched_naquadah_firebox_casing"))
            .where("e", Predicates.controller(Predicates.blocks(definition.get())))
            .where("f", Predicates.blocks("kubejs:polycarbonate_casing"))
            .where("g", $StarTVacuumPumpPredicates.vacuumPumps())
            .where("h", Predicates.blocks("kubejs:reinforced_fusion_glass"))
            .where("i", Predicates.blocks("kubejs:enriched_naquadah_pipe_casing"))
            .where("j", Predicates.blocks("gtceu:void_frame"))
            .build())
         .workableCasingModel("kubejs:block/casings/naquadah/casing", "gtceu:block/machines/chemical_reactor");
        
});